# Generated by Django 3.0.8 on 2020-08-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200802_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ocr_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_info', to='reports.Report'),
        ),
    ]
